name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "ab09827"
          password: "Hemant@#1975"

      # Step 4: Build backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t backend-app ./backend

      # Step 5: Tag and push backend Docker image
      - name: Push backend Docker image
        run: |
          docker tag backend-app:latest ab09827/backend-app:latest
          docker push ab09827/backend-app:latest

      # Step 6: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 7: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./backend/deployment.yaml --validate=false
