name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest

      # Build backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t backend-app ./backend

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push backend Docker image
      - name: Push backend Docker image
        run: |
          docker tag backend-app:latest ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Set up kubeconfig
      - name: Set up kubeconfig
        run: |
          echo "$KUBECONFIG_CONTENT" | base64 -d > $HOME/.kube/config

      # Verify kubectl config
      - name: Verify kubectl config
        run: |
          kubectl config view

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./backend/deployment.yaml
